package bflow.income.mapper;

import bflow.common.mapper.BaseMapperConfig;
import bflow.income.DTO.IncomeRequest;
import bflow.income.DTO.IncomeResponse;
import bflow.income.entity.Income;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

/** Maps income entities to API responses. */
@Mapper(config = BaseMapperConfig.class)
public interface IncomeMapper {

    /**
     * Maps an income, including its related category, wallet and contributor.
     *
     * @param income income entity
     * @return income response
     */
    @Mapping(target = "walletId", source = "wallet.id")
    @Mapping(target = "walletName", source = "wallet.name")
    @Mapping(target = "contributorId", source = "contributor.id")
    @Mapping(target = "contributorName", source = "contributor.email")
    IncomeResponse toResponse(Income income);

    /** Maps the reduced income shape used by wallet summaries. */
    @Mapping(target = "category", ignore = true)
    @Mapping(target = "source", ignore = true)
    @Mapping(target = "confidenceScore", ignore = true)
    @Mapping(target = "categorizationChanges", ignore = true)
    @Mapping(target = "editCount", ignore = true)
    @Mapping(target = "recurrencePattern", ignore = true)
    @Mapping(target = "recurringTransactionId", ignore = true)
    @Mapping(target = "walletId", source = "wallet.id")
    @Mapping(target = "walletName", source = "wallet.name")
    @Mapping(target = "contributorId", source = "contributor.id")
    @Mapping(target = "contributorName", source = "contributor.email")
    IncomeResponse toWalletSummary(Income income);

    /** Updates request-owned fields while preserving relationships. */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "wallet", ignore = true)
    @Mapping(target = "category", ignore = true)
    @Mapping(target = "contributor", ignore = true)
    @Mapping(target = "source", ignore = true)
    @Mapping(target = "recurring", ignore = true)
    @Mapping(target = "recurringTransactionId", ignore = true)
    @Mapping(target = "receiptFile", ignore = true)
    @Mapping(target = "autoGenerated", ignore = true)
    void updateFromRequest(
            IncomeRequest request,
            @MappingTarget Income income
    );
}
