package bflow.expenses.mapper;

import bflow.common.mapper.BaseMapperConfig;
import bflow.expenses.DTO.ExpenseRequest;
import bflow.expenses.DTO.ExpenseResponse;
import bflow.expenses.entity.Expense;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

/** Maps expense entities to API responses. */
@Mapper(config = BaseMapperConfig.class)
public interface ExpenseMapper {

    /**
     * Maps an expense, including its related category, wallet and contributor.
     *
     * @param expense expense entity
     * @return expense response
     */
    @Mapping(target = "walletId", source = "wallet.id")
    @Mapping(target = "walletName", source = "wallet.name")
    @Mapping(target = "contributorId", source = "contributor.id")
    @Mapping(target = "contributorName", source = "contributor.email")
    @Mapping(target = "receiptFileId", source = "receiptFile.id")
    ExpenseResponse toResponse(Expense expense);

    /** Maps the reduced transaction shape used by wallet summaries. */
    @Mapping(target = "category", ignore = true)
    @Mapping(target = "source", ignore = true)
    @Mapping(target = "confidenceScore", ignore = true)
    @Mapping(target = "categorizationChanges", ignore = true)
    @Mapping(target = "editCount", ignore = true)
    @Mapping(target = "recurrencePattern", ignore = true)
    @Mapping(target = "recurringTransactionId", ignore = true)
    @Mapping(target = "receiptFileId", ignore = true)
    @Mapping(target = "walletId", source = "wallet.id")
    @Mapping(target = "walletName", source = "wallet.name")
    @Mapping(target = "contributorId", source = "contributor.id")
    @Mapping(target = "contributorName", source = "contributor.email")
    ExpenseResponse toWalletSummary(Expense expense);

    /** Maps the reduced shape returned by quick-expense creation. */
    @Mapping(target = "category", ignore = true)
    @Mapping(target = "recurrencePattern", ignore = true)
    @Mapping(target = "recurringTransactionId", ignore = true)
    @Mapping(target = "receiptFileId", ignore = true)
    @Mapping(target = "categorizationChanges", ignore = true)
    @Mapping(target = "editCount", ignore = true)
    @Mapping(target = "walletId", source = "wallet.id")
    @Mapping(target = "walletName", source = "wallet.name")
    @Mapping(target = "contributorId", source = "contributor.id")
    @Mapping(target = "contributorName", source = "contributor.email")
    ExpenseResponse toQuickResponse(Expense expense);

    /** Updates request-owned fields while preserving relationships. */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "wallet", ignore = true)
    @Mapping(target = "category", ignore = true)
    @Mapping(target = "contributor", ignore = true)
    @Mapping(target = "source", ignore = true)
    @Mapping(target = "recurring", ignore = true)
    @Mapping(target = "recurringTransactionId", ignore = true)
    @Mapping(target = "receiptFile", ignore = true)
    @Mapping(target = "isDefault", ignore = true)
    @Mapping(target = "autoGenerated", ignore = true)
    void updateFromRequest(
            ExpenseRequest request,
            @MappingTarget Expense expense
    );
}
