package bflow.transactionimport.service;

import bflow.auth.entities.User;
import bflow.auth.repository.RepositoryUser;
import bflow.budget.services.BudgetService;
import bflow.category.RepositoryCategory;
import bflow.category.entity.Category;
import bflow.common.exception.ResourceNotFoundException;
import bflow.expenses.RepositoryExpense;
import bflow.expenses.entity.Expense;
import bflow.income.RepositoryIncome;
import bflow.income.entity.Income;
import bflow.transactionimport.dto.ImportRowResult;
import bflow.transactionimport.enums.ImportTransactionType;
import bflow.transactionimport.model.ParsedRow;
import bflow.wallet.entities.Wallet;
import bflow.wallet.repository.RepositoryWallet;
import bflow.wallet.service.ServiceWallet;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

/**
 * Persists one transaction-import batch in a single, isolated
 * transaction. Extracted as its own bean (mirrors
 * RecurringTransactionExecutor) so REQUIRES_NEW actually takes
 * effect — a private method on the calling service would bypass the
 * Spring AOP proxy. Format-agnostic: works the same whether the rows
 * came from CSV or any future importer.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class CsvImportBatchExecutor {

    /** Repository for wallet entity operations. */
    private final RepositoryWallet repositoryWallet;

    /** Repository for user entity operations. */
    private final RepositoryUser repositoryUser;

    /** Repository for category entity operations. */
    private final RepositoryCategory repositoryCategory;

    /** Repository for expense entity operations. */
    private final RepositoryExpense repositoryExpense;

    /** Repository for income entity operations. */
    private final RepositoryIncome repositoryIncome;

    /** Service for wallet balance operations. */
    private final ServiceWallet serviceWallet;

    /** Service for budget business logic operations. */
    private final BudgetService serviceBudget;

    /**
     * Persists a single batch of already-validated rows in one
     * transaction: one wallet lock, one balance adjustment per
     * direction, one saveAll per entity type, and one budget
     * evaluation per distinct expense category touched.
     *
     * @param walletId target wallet, locked once for the whole batch
     * @param userId authenticated user, recorded as contributor
     * @param batch validated rows to persist
     * @return per-row outcomes keyed by row number
     */
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public Map<Integer, ImportRowResult> executeBatch(
            final UUID walletId,
            final UUID userId,
            final List<ParsedRow> batch
    ) {
        Wallet wallet = repositoryWallet.findByIdForUpdate(walletId)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "Wallet not found"
                ));

        User contributor = repositoryUser.findById(userId)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "Authenticated user not found"
                ));

        Map<Integer, ImportRowResult> outcomes = new LinkedHashMap<>();

        List<Expense> expenses = new ArrayList<>();
        List<Integer> expenseRows = new ArrayList<>();
        List<Income> incomes = new ArrayList<>();
        List<Integer> incomeRows = new ArrayList<>();

        BigDecimal expenseTotal = BigDecimal.ZERO;
        BigDecimal incomeTotal = BigDecimal.ZERO;
        Set<UUID> touchedExpenseCategories = new LinkedHashSet<>();

        for (ParsedRow row : batch) {
            BigDecimal amount = row.amount().setScale(2, RoundingMode.HALF_EVEN);
            Category category = repositoryCategory.getReferenceById(
                    row.categoryId()
            );

            if (ImportTransactionType.EXPENSE.name().equals(row.type())) {
                Expense expense = new Expense();
                expense.setTitle(row.title());
                expense.setDescription(row.description());
                expense.setAmount(amount);
                expense.setDate(row.date());
                expense.setWallet(wallet);
                expense.setContributor(contributor);
                expense.setCategory(category);
                expense.setSource("import");
                expense.setAutoGenerated(false);
                expense.setRecurring(false);

                expenses.add(expense);
                expenseRows.add(row.rowNumber());
                expenseTotal = expenseTotal.add(amount);
                touchedExpenseCategories.add(row.categoryId());
            } else {
                Income income = new Income();
                income.setTitle(row.title());
                income.setDescription(row.description());
                income.setAmount(amount);
                income.setDate(row.date());
                income.setWallet(wallet);
                income.setContributor(contributor);
                income.setCategory(category);
                income.setSource("import");
                income.setRecurring(false);

                incomes.add(income);
                incomeRows.add(row.rowNumber());
                incomeTotal = incomeTotal.add(amount);
            }
        }

        if (!expenses.isEmpty()) {
            serviceWallet.subtractBalance(wallet, expenseTotal);
            List<Expense> saved = repositoryExpense.saveAll(expenses);
            repositoryExpense.flush();
            for (int i = 0; i < saved.size(); i++) {
                outcomes.put(expenseRows.get(i), ImportRowResult.ok(
                        expenseRows.get(i), "EXPENSE",
                        saved.get(i).getId().toString()
                ));
            }
        }

        if (!incomes.isEmpty()) {
            serviceWallet.addBalance(wallet, incomeTotal);
            List<Income> saved = repositoryIncome.saveAll(incomes);
            repositoryIncome.flush();
            for (int i = 0; i < saved.size(); i++) {
                outcomes.put(incomeRows.get(i), ImportRowResult.ok(
                        incomeRows.get(i), "INCOME",
                        saved.get(i).getId().toString()
                ));
            }
        }

        for (UUID categoryId : touchedExpenseCategories) {
            serviceBudget.evaluateBudgetsForExpenseEvent(walletId, categoryId);
        }

        log.debug(
                "Batch executed for walletId={}: {} expenses, {} incomes",
                walletId, expenses.size(), incomes.size()
        );

        return outcomes;
    }
}