package bflow.expenses.services;

import bflow.auth.services.UserService;
import bflow.budget.services.BudgetService;
import bflow.common.exception.ResourceNotFoundException;
import bflow.common.financial.TransactionMapper;
import bflow.common.i18n.MessageService;
import bflow.expenses.DTO.QuickExpenseRequest;
import bflow.expenses.DTO.ExpenseResponse;
import bflow.expenses.RepositoryExpense;
import bflow.expenses.entity.Expense;
import bflow.wallet.entities.Wallet;
import bflow.wallet.entities.WalletUser;
import bflow.wallet.enums.WalletRole;
import bflow.wallet.repository.RepositoryWallet;
import bflow.wallet.repository.RepositoryWalletUser;
import bflow.wallet.service.ServiceWallet;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class QuickExpenseService {
    /** Source marker used by the transaction history and clients. */
    private static final String QUICK_EXPENSE_SOURCE = "quick";

    /** Title assigned when no transaction detail is requested from the user. */
    private static final String QUICK_EXPENSE_TITLE = "Quick expense";

    /** Confidence for an intentionally category-free quick expense. */
    private static final double NO_CATEGORY_CONFIDENCE = 0.0;

    /**
     * Repository for expense operations.
     */
    private final RepositoryExpense repositoryExpense;

    /**
     * Repository for wallet operations, used to acquire a pessimistic
     * lock on the target wallet before mutating its balance.
     */
    private final RepositoryWallet repositoryWallet;

    /**
     * Service encapsulating wallet balance mutations.
     */
    private final ServiceWallet serviceWallet;

    /**
     * Service for user business logic operations.
     */
    private final UserService userService;

    /**
     * Repository for wallet user relationships.
     */
    private final RepositoryWalletUser walletUserRepository;

    /**
     * Service for budget operations.
     */
    private final BudgetService budgetService;

    /** Service for resolving localized messages. */
    private final MessageService messageService;

    /**
     * Create a quick expense for a user.
     *
     * @param userId the user ID
     * @param request the quick expense request
     * @return the created expense response
     */
    @Transactional
    public ExpenseResponse createQuickExpense(
            final UUID userId,
            final QuickExpenseRequest request
    ) {
        userService.validateUserActive(userId);

        WalletUser walletUser = walletUserRepository
            .findFirstByUserIdAndRoleOrderByDefaultWalletDescCreatedAtAsc(
                    userId, WalletRole.OWNER)
            .orElseThrow(() ->
                new ResourceNotFoundException(messageService.get("noWalletFound"))
        );

        // Lock the wallet row for the duration of this transaction so
        // the balance read-modify-write below can't race with a
        // concurrent expense/income/transfer touching the same wallet.
        Wallet wallet = repositoryWallet
                .findByIdForUpdate(walletUser.getWallet().getId())
                .orElseThrow(() -> new ResourceNotFoundException(
                        messageService.get("wallet.notFound")
                ));

        BigDecimal amount =
                request.getAmount().setScale(2, RoundingMode.HALF_EVEN);

        Expense expense = new Expense();

        expense.setAmount(amount);
        expense.setTitle(QUICK_EXPENSE_TITLE);
        expense.setDate(LocalDate.now());

        expense.setWallet(wallet);
        expense.setCategory(null);

        expense.setContributor(walletUser.getUser());

        expense.setSource(QUICK_EXPENSE_SOURCE);
        expense.setAutoGenerated(true);
        expense.setConfidenceScore(NO_CATEGORY_CONFIDENCE);

        expense.setRecurring(false);

        // Fix for both balance-duplication exploits: without this
        // line the wallet balance was never debited on creation, so a
        // later PUT/DELETE on this same expense via ControllerExpense
        // would credit the balance for an amount that was never
        // subtracted in the first place.
        serviceWallet.subtractBalance(wallet, amount);

        Expense saved = repositoryExpense.save(expense);

        budgetService.evaluateBudgetsForExpenseEvent(
                wallet.getId(),
                null
        );

        return toResponse(saved);
    }

    private ExpenseResponse toResponse(final Expense e) {
        return TransactionMapper.mapQuickExpenseToResponse(e);
    }

}
