package bflow.expenses.services;

import bflow.budget.services.BudgetService;
import bflow.category.entity.Category;
import bflow.expenses.DTO.QuickExpenseRequest;
import bflow.expenses.DTO.ExpenseResponse;
import bflow.expenses.RepositoryExpense;
import bflow.expenses.entity.Expense;
import bflow.merchant.MerchantDetectionService;
import bflow.wallet.RepositoryWalletUser;
import bflow.wallet.entities.Wallet;
import bflow.wallet.entities.WalletUser;
import bflow.wallet.enums.WalletRole;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDate;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class QuickExpenseService {
    /**
     * Maximum length for generated title.
     */
    private static final int MAX_TITLE_LENGTH = 30;

    /**
     * High confidence score for merchant detection.
     */
    private static final double HIGH_CONFIDENCE = 0.8;

    /**
     * Low confidence score for merchant detection.
     */
    private static final double LOW_CONFIDENCE = 0.3;

    /**
     * Repository for expense operations.
     */
    private final RepositoryExpense repositoryExpense;

    /**
     * Service for merchant category detection.
     */
    private final MerchantDetectionService merchantDetectionService;

    /**
     * Repository for wallet user relationships.
     */
    private final RepositoryWalletUser walletUserRepository;

    /**
     * Service for budget operations.
     */
    private final BudgetService budgetService;

    /**
     * Create a quick expense for a user.
     *
     * @param userId the user ID
     * @param request the quick expense request
     * @return the created expense response
     */
    @Transactional
    public ExpenseResponse createQuickExpense(
            final UUID userId,
            final QuickExpenseRequest request
    ) {
        WalletUser walletUser = walletUserRepository
            .findFirstByUserIdAndRole(userId, WalletRole.OWNER)
            .orElseThrow(() ->
                new RuntimeException("No wallet found")
        );

        Wallet wallet = walletUser.getWallet();

        String normalized = normalize(request.getDescription());

        Category category = merchantDetectionService.detectCategory(normalized);

        Expense expense = new Expense();

        expense.setAmount(request.getAmount());
        expense.setDescription(request.getDescription());
        expense.setTitle(generateTitle(request.getDescription()));
        expense.setDate(LocalDate.now());

        expense.setWallet(wallet);
        expense.setCategory(category);

        expense.setContributor(walletUser.getUser());

        expense.setSource("quick");
        expense.setAutoGenerated(true);
        expense.setConfidenceScore(category != null ? HIGH_CONFIDENCE
                : LOW_CONFIDENCE);

        expense.setRecurring(false);
        expense.setTaxDeductible(false);
        expense.setReimbursable(false);

        Expense saved = repositoryExpense.save(expense);

        budgetService.evaluateBudgetsForWallet(wallet.getId());

        return toResponse(saved);
    }

    private String normalize(final String input) {
        if (input == null) {
            return "";
        }

        return input
                .toLowerCase()
                .replaceAll("[^\\p{L}\\p{N} ]", "")
                .trim();
    }

    private String generateTitle(final String description) {
        if (description == null || description.isBlank()) {
            return "Quick expense";
        }

        return description.length() > MAX_TITLE_LENGTH
                ? description.substring(0, MAX_TITLE_LENGTH)
                : description;
    }

    private ExpenseResponse toResponse(final Expense e) {

        ExpenseResponse r = new ExpenseResponse();

        r.setId(e.getId().toString());

        r.setTitle(e.getTitle());
        r.setDescription(e.getDescription());

        r.setAmount(e.getAmount());

        r.setDate(e.getDate());

        r.setTaxDeductible(e.getTaxDeductible());
        r.setRecurring(e.getRecurring());
        r.setReimbursable(e.getReimbursable());

        r.setSource(e.getSource());

        r.setConfidenceScore(e.getConfidenceScore());

        r.setCreatedAt(e.getCreatedAt());

        if (e.getWallet() != null) {
            r.setWalletId(e.getWallet().getId().toString());
            r.setWalletName(e.getWallet().getName());
        }

        if (e.getContributor() != null) {
            r.setContributorId(
                    e.getContributor().getId().toString()
            );

            r.setContributorName(
                    e.getContributor().getEmail()
            );
        }

        return r;
    }

}
